import assert from "node:assert/strict";import fs from "node:fs";import path from "node:path";import {describe,it} from "node:test";import {resolveAttendeeAccess,resolveMusicalTicketAccess,type OwnedEntitlement} from "../../registration/entitlements.ts";
const root=process.cwd(),read=(p:string)=>fs.readFileSync(path.join(root,p),"utf8"),migration=read("supabase/migrations/20260807050000_registration_slice5_access_checkin.sql"),api=read("app/api/owner/check-in/route.ts"),ui=read("components/owner/CheckInOperationsClient.tsx"),auth=read("lib/owner/auth.ts"),repository=read("lib/access/check-in.ts");
const occurrence={id:"occ-1",eventId:"event-1",eventType:"worship",startsAt:"2026-08-07T19:00:00.000Z"};const entitlement=(over:Partial<OwnedEntitlement>={}):OwnedEntitlement=>({id:"ent-1",key:"GENERAL_ENTRY",name:"General",type:"event_access",active:true,eventType:"worship",eventId:null,eventOccurrenceId:null,venueKey:null,accessZone:"general",validFrom:null,validUntil:null,preferredHoldMinutes:null,usageLimit:null,singleUse:false,guardianRequired:false,status:"active",quantity:1,usesConsumed:0,guardianRegistrationId:null,...over});
describe("registration Slice 5 access/check-in",()=>{
it("1 valid registration credential resolves",()=>assert.equal(resolveAttendeeAccess({registrationStatus:"confirmed",credentialStatus:"active",eventOccurrence:occurrence,entitlements:[entitlement()],currentTime:"2026-08-07T18:00:00Z"}).result,"ALLOWED"));
it("2 revoked credential denied",()=>assert.equal(resolveAttendeeAccess({registrationStatus:"confirmed",credentialStatus:"revoked",eventOccurrence:occurrence,entitlements:[entitlement()],currentTime:new Date()}).reasonCode,"CREDENTIAL_REVOKED"));
it("3 canceled registration denied",()=>assert.equal(resolveAttendeeAccess({registrationStatus:"canceled",credentialStatus:"active",eventOccurrence:occurrence,entitlements:[entitlement()],currentTime:new Date()}).reasonCode,"REGISTRATION_CANCELED"));
it("4 pending payment denied",()=>assert.equal(resolveAttendeeAccess({registrationStatus:"payment_pending",credentialStatus:"active",eventOccurrence:occurrence,entitlements:[entitlement()],currentTime:new Date()}).reasonCode,"PAYMENT_NOT_CONFIRMED"));
it("5 attendee cannot invoke scanner API",()=>assert.match(api,/requireCheckInUser/));
it("6 correct occurrence allowed",()=>assert.equal(resolveAttendeeAccess({registrationStatus:"confirmed",credentialStatus:"active",eventOccurrence:occurrence,entitlements:[entitlement({eventOccurrenceId:"occ-1"})],currentTime:new Date()}).result,"ALLOWED"));
it("7 wrong occurrence denied",()=>assert.equal(resolveAttendeeAccess({registrationStatus:"confirmed",credentialStatus:"active",eventOccurrence:occurrence,entitlements:[entitlement({eventOccurrenceId:"other"})],currentTime:new Date()}).result,"DENIED"));
it("8 wrong zone is server controlled",()=>assert.match(migration,/WRONG_ZONE/));
it("9 General access correct",()=>assert.equal(resolveAttendeeAccess({registrationStatus:"confirmed",credentialStatus:"active",eventOccurrence:occurrence,entitlements:[entitlement()],currentTime:new Date()}).reasonCode,"GENERAL_SEATING"));
it("10 Diamond preferred access correct",()=>assert.equal(resolveAttendeeAccess({registrationStatus:"confirmed",credentialStatus:"active",eventOccurrence:occurrence,entitlements:[entitlement({type:"seating",preferredHoldMinutes:15,accessZone:"preferred"})],currentTime:"2026-08-07T19:10:00Z"}).reasonCode,"PREFERRED_SEATING"));
it("11 preferred cutoff behavior correct",()=>assert.equal(resolveAttendeeAccess({registrationStatus:"confirmed",credentialStatus:"active",eventOccurrence:occurrence,entitlements:[entitlement({type:"seating",preferredHoldMinutes:15,accessZone:"preferred"}),entitlement()],currentTime:"2026-08-07T19:20:00Z"}).result,"ALLOWED_WITH_CONDITION"));
it("12 general remains after preferred cutoff",()=>assert.match(migration,/PREFERRED_WINDOW_EXPIRED/));
it("13 valid Musical ticket allowed",()=>assert.equal(resolveMusicalTicketAccess({ticketStatus:"valid",ticketOccurrenceId:"occ-1",requestedOccurrenceId:"occ-1"}).result,"ALLOWED"));
it("14 no Musical ticket denied",()=>assert.equal(resolveMusicalTicketAccess({ticketStatus:"pending",ticketOccurrenceId:"occ-1",requestedOccurrenceId:"occ-1"}).reasonCode,"MUSICAL_TICKET_REQUIRED"));
it("15 revoked Musical ticket denied",()=>assert.equal(resolveMusicalTicketAccess({ticketStatus:"revoked",ticketOccurrenceId:"occ-1",requestedOccurrenceId:"occ-1"}).result,"DENIED"));
it("16 wrong Musical occurrence denied",()=>assert.equal(resolveMusicalTicketAccess({ticketStatus:"valid",ticketOccurrenceId:"other",requestedOccurrenceId:"occ-1"}).reasonCode,"WRONG_EVENT"));
it("17 single entry first scan is atomic",()=>assert.match(migration,/FOR UPDATE/));
it("18 second scan already used",()=>assert.match(migration,/TICKET_ALREADY_USED/));
it("19 simultaneous duplicate has unique check-in guards",()=>assert.match(migration,/check_ins_ticket_single_idx/));
it("20 reentry is configurable",()=>assert.match(migration,/REENTRY_ALLOWED/));
it("21 failed validation does not consume",()=>assert.match(migration,/IF decision IN\('ALLOWED','ALLOWED_WITH_CONDITION'\)/));
it("22 Junior guardian relationship is server checked",()=>assert.match(migration,/guardian_registration_id/));
it("23 guardian required response",()=>assert.equal(resolveAttendeeAccess({registrationStatus:"confirmed",credentialStatus:"active",eventOccurrence:occurrence,entitlements:[entitlement({guardianRequired:true})],currentTime:new Date()}).reasonCode,"GUARDIAN_REQUIRED"));
it("24 group members retain individual credentials",()=>assert.match(migration,/credential_id uuid NULL/));
it("25 authorized staff scanner access",()=>assert.match(auth,/permission.*CHECK_IN/));
it("26 unauthorized user rejected",()=>assert.match(auth,/status: 403/));
it("27 recent scans visible",()=>assert.match(repository,/access_scan_attempts/));
it("28 dashboard counts are computed from real rows",()=>assert.match(repository,/const stats=/));
it("29 CSV export protected",()=>assert.match(api,/format.*csv[\s\S]*isOwner/));
it("30 invalid QR denied",()=>assert.match(repository,/INVALID_CREDENTIAL/));
it("31 malformed token denied before RPC",()=>assert.match(repository,/isValidCredentialToken/));
it("32 expired entitlement denied",()=>assert.equal(resolveAttendeeAccess({registrationStatus:"confirmed",credentialStatus:"active",eventOccurrence:occurrence,entitlements:[entitlement({validUntil:"2026-01-01T00:00:00Z"})],currentTime:"2026-08-07T00:00:00Z"}).reasonCode,"ENTITLEMENT_EXPIRED"));
it("33 server failure fails closed",()=>assert.match(api,/VALIDATION_UNAVAILABLE/));
it("camera requests real media only after action",()=>{assert.match(ui,/getUserMedia/);assert.match(ui,/START SCANNER/)});
it("no demo credentials or seeded access configuration",()=>assert.doesNotMatch(migration,/INSERT INTO (public\.)?(access_zones|staff_permissions)\s*\(/i));
});
