"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useCallback, useEffect, useState } from "react";
import RegistrationPolicyDocument from "@/components/registration/RegistrationPolicyDocument";

const input="rounded border border-white/10 bg-black p-3";
const dateValue=(value:string)=>value?new Date(value).toISOString().slice(0,16):"";

export default function RegistrationManagementClient(){
  const [data,setData]=useState<any>({registrations:[],products:[],policies:[]}),[q,setQ]=useState(""),[status,setStatus]=useState(""),[product,setProduct]=useState(""),[error,setError]=useState(""),[editing,setEditing]=useState<any>(null),[preview,setPreview]=useState<any>(null);
  const load=useCallback(async()=>{const p=new URLSearchParams({q,status,product});const r=await fetch(`/api/owner/registrations?${p}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j);},[q,status,product]);
  useEffect(()=>{const id=setTimeout(()=>void load().catch(e=>setError(e.message)),150);return()=>clearTimeout(id);},[load]);
  async function mutate(method:string,body:any){setError("");const r=await fetch("/api/owner/registrations",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error);await load();}
  async function createPolicy(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await mutate("POST",{action:"create_policy",version:f.get("version"),title:f.get("title"),effectiveAt:f.get("effectiveAt"),content:f.get("content")});e.currentTarget.reset();}catch(e){setError(e instanceof Error?e.message:"Unable to create policy.");}}
  async function saveDraft(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await mutate("PATCH",{action:"edit_policy",id:editing.id,title:f.get("title"),effectiveAt:f.get("effectiveAt"),content:f.get("content")});setEditing(null);}catch(e){setError(e instanceof Error?e.message:"Unable to edit policy.");}}
  const patch=(body:any)=>mutate("PATCH",body).catch(e=>setError(e.message));
  async function publishPolicy(policy:any){
    const active=data.policies.find((item:any)=>item.status==="published");
    const acknowledgeSupersede=Boolean(active);
    if(active&&!window.confirm(`Publish ${policy.version} and supersede active policy ${active.version}? The historical policy and all prior acceptance evidence will be preserved.`))return;
    try{await mutate("PATCH",{action:"publish_policy",id:policy.id,acknowledgeSupersede});}catch(e){setError(e instanceof Error?e.message:"Unable to publish policy.");}
  }
  const registrantName=(id:string|null)=>{const row=data.registrations.find((item:any)=>item.id===id);return row?`${row.first_name} ${row.last_name}`:"Unavailable";};
  return <div className="grid gap-3">
    <section className="rounded border border-white/10 bg-[#080b18] p-4"><h2 className="text-xl font-bold">Registration management</h2><div className="mt-3 grid gap-2 md:grid-cols-3"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search attendee or email" className={input}/><select value={status} onChange={e=>setStatus(e.target.value)} className={input}><option value="">All statuses</option>{["draft","submitted","payment_pending","confirmed","canceled","refunded"].map(x=><option key={x}>{x}</option>)}</select><select value={product} onChange={e=>setProduct(e.target.value)} className={input}><option value="">All products</option>{data.products.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div>{error?<p role="alert" className="mt-2 text-red-300">{error}</p>:null}<div className="mt-3 grid gap-2">{data.registrations.length?data.registrations.map((r:any)=><details key={r.id} className="rounded border border-white/10 p-3"><summary>{r.first_name} {r.last_name} · {r.status} · {r.registration_products?.name||"No product"}</summary><div className="mt-2 grid gap-1 text-sm text-white/70"><p>{r.email||"Group member"}{r.mobile_phone?` · ${r.mobile_phone}`:""}</p><p>{r.is_primary_registrant?"Primary registrant":`Group member: ${r.relationship_to_primary}`}{r.guardian_registration_id?` · Guardian: ${registrantName(r.guardian_registration_id)}`:""}</p><p>Payment: {r.registration_payments?.[0]?.status||"No payment"} · Confirmation: {r.confirmation_reference||"Pending"}</p><p>Interpretation: {r.requires_interpretation?`Yes — ${r.preferred_language}`:"No"}</p><p>Credential: {r.registration_credentials?.at(-1)?.status||"Not issued"}</p><p>Policy: {r.registration_groups?.registration_policy_acceptances?.[0]?.policy_version||"Not accepted"} {r.registration_groups?.registration_policy_acceptances?.[0]?.accepted_at?`· ${new Date(r.registration_groups.registration_policy_acceptances[0].accepted_at).toLocaleString()} · Authorized: ${r.registration_groups.registration_policy_acceptances[0].authorized_signer_name} · Agreement: ${r.registration_groups.registration_policy_acceptances[0].agreement_signer_name}`:""}</p>{["draft","submitted","payment_pending"].includes(r.status)?<button className="mt-2 w-fit rounded border border-red-400/40 px-3 py-2" onClick={()=>void patch({action:"cancel_registration",id:r.id})}>Cancel registration</button>:null}</div></details>):<p>No registrations match these filters.</p>}</div></section>
    <section className="rounded border border-white/10 bg-[#080b18] p-4"><h2 className="text-xl font-bold">Policy versions</h2><p className="text-sm text-white/60">Published and accepted versions are immutable. Create a new draft to revise policy language.</p><form onSubmit={createPolicy} className="mt-3 grid gap-2"><input required name="version" placeholder="Version" className={input}/><input required name="title" placeholder="Policy title" className={input}/><input required name="effectiveAt" type="datetime-local" className={input}/><textarea required name="content" rows={10} placeholder="Approved policy text" className={input}/><button className="rounded bg-purple-700 p-3">Create draft version</button></form>
      <div className="mt-4 grid gap-2">{data.policies.map((p:any)=><article key={p.id} className="rounded border border-white/10 p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><strong>{p.version} · {p.title}</strong><p className="capitalize">{p.status}{p.status==="published"?" · Active":""} · {p.acceptanceCount} acceptance{p.acceptanceCount===1?"":"s"}</p><p className="text-xs text-white/55">Effective {new Date(p.effective_at).toLocaleString()}{p.published_at?` · Published ${new Date(p.published_at).toLocaleString()}`:""}{p.superseded_at?` · Retired/superseded ${new Date(p.superseded_at).toLocaleString()}`:""}</p><p className="text-xs text-white/55">Created by {p.created_by||"Unavailable"} · Last updated by {p.updated_by||"Unavailable"}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>setPreview(p)}>Preview</button>{p.status==="draft"?<><button onClick={()=>setEditing(p)}>Edit draft</button><button onClick={()=>void publishPolicy(p)}>{data.policies.some((item:any)=>item.status==="published")?"Publish & supersede active":"Publish"}</button></>:null}{p.status==="published"?<button className="text-red-200" onClick={()=>void patch({action:"retire_policy",id:p.id})}>Retire</button>:null}</div></div></article>)}</div>
    </section>
    {editing?<div role="dialog" aria-modal="true" aria-label="Edit policy draft" className="fixed inset-0 z-[100] grid place-items-center bg-black/80 p-4"><form onSubmit={saveDraft} className="grid max-h-[90vh] w-full max-w-3xl gap-3 overflow-auto rounded-xl bg-[#0b0715] p-6"><h2>Edit draft {editing.version}</h2><input required name="title" defaultValue={editing.title} className={input}/><input required name="effectiveAt" type="datetime-local" defaultValue={dateValue(editing.effective_at)} className={input}/><textarea required name="content" rows={16} defaultValue={editing.content} className={input}/><div className="flex gap-2"><button className="rounded bg-purple-700 px-4 py-2">Save draft</button><button type="button" onClick={()=>setEditing(null)}>Cancel</button></div></form></div>:null}
    {preview?<div role="dialog" aria-modal="true" aria-label="Policy preview" className="fixed inset-0 z-[100] grid place-items-center bg-black/80 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-xl bg-[#0b0715] p-6"><RegistrationPolicyDocument title={preview.title} version={preview.version} content={preview.content} effectiveAt={preview.effective_at}/><button className="mt-4 rounded bg-purple-700 px-4 py-2" onClick={()=>setPreview(null)}>Close preview</button></div></div>:null}
  </div>;
}
