"use client";

import { useCallback, useEffect, useState } from "react";

type Product = { id:string; product_key:string; name:string; description:string|null; price_cents:number; active:boolean; public:boolean };
type Entitlement = { id:string; entitlement_key:string; name:string; entitlement_type:string; event_type:string|null; access_zone:string|null; preferred_hold_minutes:number|null; guardian_required:boolean; active:boolean };
type Assignment = { id:string; registration_product_id:string; entitlement_id:string; active:boolean };

export default function RegistrationProductAccessClient() {
  const [data, setData] = useState<{products:Product[];entitlements:Entitlement[];assignments:Assignment[]}>({products:[],entitlements:[],assignments:[]});
  const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const response=await fetch("/api/owner/registration-products",{cache:"no-store"});const json=await response.json();if(!response.ok) throw new Error(json.error||"Unable to load configuration.");setData(json);},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>{void load().catch((e)=>setError(e.message));},0);return()=>window.clearTimeout(timer);},[load]);
  async function submit(event:React.FormEvent<HTMLFormElement>,kind:"product"|"entitlement") { event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);const body=kind==="product"?{kind,productKey:form.get("key"),name:form.get("name"),description:form.get("description"),eligibilityDescription:form.get("eligibility"),priceCents:Math.round(Number(form.get("price"))*100),registrationOpensAt:form.get("opens"),registrationClosesAt:form.get("closes"),capacity:form.get("capacity"),badgeType:form.get("badgeType"),sortOrder:Number(form.get("sortOrder")),public:form.get("public")==="on"}:{kind,entitlementKey:form.get("key"),name:form.get("name"),description:form.get("description"),entitlementType:form.get("type"),eventType:form.get("eventType"),eventId:form.get("eventId"),eventOccurrenceId:form.get("eventOccurrenceId"),venueKey:form.get("venueKey"),accessZone:form.get("accessZone"),validFrom:form.get("validFrom"),validUntil:form.get("validUntil"),preferredHoldMinutes:form.get("hold"),usageLimit:form.get("usageLimit"),guardianRequired:form.get("guardian")==="on",singleUse:form.get("singleUse")==="on"};try{const response=await fetch("/api/owner/registration-products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const json=await response.json();if(!response.ok)throw new Error(json.error);event.currentTarget.reset();await load();}catch(e){setError(e instanceof Error?e.message:"Unable to save.");}finally{setBusy(false);}}
  async function assign(productId:string,entitlementId:string){if(!entitlementId)return;setBusy(true);setError("");try{const response=await fetch("/api/owner/registration-products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"assignment",productId,entitlementId})});const json=await response.json();if(!response.ok)throw new Error(json.error);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to assign.");}finally{setBusy(false);}}
  async function toggle(kind:"product"|"entitlement"|"assignment",id:string,active:boolean){setBusy(true);try{const response=await fetch("/api/owner/registration-products",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,id,active})});if(!response.ok)throw new Error((await response.json()).error);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to update.");}finally{setBusy(false);}}
  return <div className="grid gap-3 xl:grid-cols-2">
    {error?<p role="alert" className="xl:col-span-2 rounded border border-red-400/40 bg-red-950/40 p-3 text-sm text-red-100">{error}</p>:null}
    <form onSubmit={(e)=>submit(e,"product")} className="grid gap-3 rounded border border-white/10 bg-[#080b18] p-4">
      <h2 className="font-headline text-2xl uppercase">Create registration product</h2><p className="text-xs text-white/55">Configure real products without granting access by name.</p>
      <input required name="key" pattern="[A-Za-z][A-Za-z0-9_]{1,63}" placeholder="Stable key, e.g. GENERAL_2026" className="rounded border border-white/15 bg-black/40 p-3"/><input required name="name" placeholder="Display name" className="rounded border border-white/15 bg-black/40 p-3"/><textarea name="description" placeholder="Description" className="rounded border border-white/15 bg-black/40 p-3"/><textarea name="eligibility" placeholder="Eligibility/approval description (informational, not automatic authorization)" className="rounded border border-white/15 bg-black/40 p-3"/><div className="grid grid-cols-2 gap-2"><label className="grid gap-1 text-xs">Price in dollars<input required name="price" type="number" min="0" step="0.01" className="rounded border border-white/15 bg-black/40 p-3"/></label><label className="grid gap-1 text-xs">Capacity<input name="capacity" type="number" min="0" className="rounded border border-white/15 bg-black/40 p-3"/></label></div><div className="grid grid-cols-2 gap-2"><label className="grid gap-1 text-xs">Registration opens<input name="opens" type="datetime-local" className="rounded border border-white/15 bg-black/40 p-3"/></label><label className="grid gap-1 text-xs">Registration closes<input name="closes" type="datetime-local" className="rounded border border-white/15 bg-black/40 p-3"/></label></div><div className="grid grid-cols-2 gap-2"><input name="badgeType" placeholder="Badge type" className="rounded border border-white/15 bg-black/40 p-3"/><input name="sortOrder" type="number" defaultValue="0" aria-label="Sort order" className="rounded border border-white/15 bg-black/40 p-3"/></div><label className="flex gap-2 text-sm"><input name="public" type="checkbox"/>Publicly selectable</label><button disabled={busy} className="min-h-11 rounded bg-[#096bff] font-bold">Create product</button>
    </form>
    <form onSubmit={(e)=>submit(e,"entitlement")} className="grid gap-3 rounded border border-white/10 bg-[#080b18] p-4">
      <h2 className="font-headline text-2xl uppercase">Create controlled entitlement</h2><input required name="key" pattern="[A-Za-z][A-Za-z0-9_]{1,63}" placeholder="Stable key, e.g. GENERAL_ENTRY" className="rounded border border-white/15 bg-black/40 p-3"/><input required name="name" placeholder="Admin-facing name" className="rounded border border-white/15 bg-black/40 p-3"/><textarea name="description" placeholder="Capability description" className="rounded border border-white/15 bg-black/40 p-3"/><select name="type" className="rounded border border-white/15 bg-black p-3"><option value="event_access">Event access</option><option value="seating">Seating</option><option value="housing">Housing</option><option value="content">Content</option><option value="item">Included item</option><option value="badge">Badge</option><option value="discount">Discount</option></select><div className="grid grid-cols-2 gap-2"><input name="eventType" placeholder="Event type (optional)" className="rounded border border-white/15 bg-black/40 p-3"/><input name="accessZone" placeholder="Access zone" className="rounded border border-white/15 bg-black/40 p-3"/><input name="eventId" placeholder="Specific event UUID" className="rounded border border-white/15 bg-black/40 p-3"/><input name="eventOccurrenceId" placeholder="Specific occurrence UUID" className="rounded border border-white/15 bg-black/40 p-3"/><input name="venueKey" placeholder="Venue key" className="rounded border border-white/15 bg-black/40 p-3"/><input name="usageLimit" type="number" min="1" placeholder="Usage limit" className="rounded border border-white/15 bg-black/40 p-3"/></div><div className="grid grid-cols-2 gap-2"><label className="grid gap-1 text-xs">Valid from<input name="validFrom" type="datetime-local" className="rounded border border-white/15 bg-black/40 p-3"/></label><label className="grid gap-1 text-xs">Valid until<input name="validUntil" type="datetime-local" className="rounded border border-white/15 bg-black/40 p-3"/></label></div><label className="grid gap-1 text-xs">Preferred hold minutes<input name="hold" type="number" min="0" className="rounded border border-white/15 bg-black/40 p-3"/></label><div className="flex gap-5 text-sm"><label><input name="guardian" type="checkbox"/> Guardian required</label><label><input name="singleUse" type="checkbox"/> Single use</label></div><button disabled={busy} className="min-h-11 rounded bg-[#7b2cbf] font-bold">Create entitlement</button>
    </form>
    <section className="xl:col-span-2 rounded border border-white/10 bg-[#080b18] p-4"><h2 className="font-headline text-2xl uppercase">Product access matrix</h2>{data.products.length===0?<p className="mt-3 text-sm text-white/55">No products configured. Create only approved real products.</p>:<div className="mt-3 grid gap-3">{data.products.map(product=><article key={product.id} className="rounded border border-white/10 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><strong>{product.name}</strong><p className="text-xs text-white/50">{product.product_key} · ${(product.price_cents/100).toFixed(2)} · {product.public?"Public":"Private"}</p></div><button disabled={busy} onClick={()=>toggle("product",product.id,!product.active)} className="rounded border border-white/15 px-3 py-2 text-xs">{product.active?"Deactivate":"Activate"}</button></div><div className="mt-3 flex flex-wrap gap-2">{data.assignments.filter(a=>a.registration_product_id===product.id&&a.active).map(a=>{const e=data.entitlements.find(x=>x.id===a.entitlement_id);return e?<button key={a.id} onClick={()=>toggle("assignment",a.id,false)} title="Remove assignment" className="rounded-full border border-purple-400/40 bg-purple-500/10 px-3 py-1 text-xs">{e.name} ×</button>:null;})}</div><label className="mt-3 flex gap-2 text-xs">Assign entitlement<select defaultValue="" onChange={(e)=>{void assign(product.id,e.target.value);e.target.value="";}} className="rounded border border-white/15 bg-black p-2"><option value="">Select…</option>{data.entitlements.filter(e=>e.active&&!data.assignments.some(a=>a.registration_product_id===product.id&&a.entitlement_id===e.id&&a.active)).map(e=><option key={e.id} value={e.id}>{e.name} ({e.entitlement_key})</option>)}</select></label></article>)}</div>}</section>
  </div>;
}
