import assert from "node:assert/strict";
import test from "node:test";
import { resolveAttendeeAccess, type OwnedEntitlement } from "../entitlements";

const occurrence = { id:"occ-worship", eventId:"event-worship", eventType:"evening_worship", venueKey:"main", startsAt:"2026-11-03T19:00:00.000Z" };
function entitlement(partial:Partial<OwnedEntitlement>):OwnedEntitlement{return { id:"entitlement",key:"GENERAL_ENTRY",name:"General entry",type:"event_access",active:true,eventType:"evening_worship",eventId:null,eventOccurrenceId:null,venueKey:null,accessZone:"general",validFrom:null,validUntil:null,preferredHoldMinutes:null,usageLimit:null,singleUse:false,guardianRequired:false,status:"active",quantity:1,usesConsumed:0,guardianRegistrationId:null,...partial };}
function resolve(entitlements:OwnedEntitlement[],currentTime="2026-11-03T19:05:00.000Z",extra:Partial<Parameters<typeof resolveAttendeeAccess>[0]>={}){return resolveAttendeeAccess({registrationStatus:"confirmed",credentialStatus:"active",eventOccurrence:occurrence,entitlements,currentTime,...extra});}

test("Diamond-style configured entitlements grant preferred seating before configurable cutoff",()=>{const result=resolve([entitlement({id:"preferred",key:"PREFERRED",type:"seating",accessZone:"preferred",preferredHoldMinutes:15}),entitlement({id:"general"})]);assert.equal(result.result,"ALLOWED");assert.equal(result.reasonCode,"PREFERRED_SEATING");assert.equal(result.preferredUntil,"2026-11-03T19:15:00.000Z");});
test("preferred window expiration preserves configured general access",()=>{const result=resolve([entitlement({id:"preferred",type:"seating",accessZone:"preferred",preferredHoldMinutes:15}),entitlement({id:"general"})],"2026-11-03T19:16:00.000Z");assert.equal(result.result,"ALLOWED_WITH_CONDITION");assert.equal(result.reasonCode,"PREFERRED_SEATING_WINDOW_EXPIRED");});
test("general access does not imply preferred seating",()=>{const result=resolve([entitlement({id:"general"})]);assert.equal(result.reasonCode,"GENERAL_SEATING");});
test("junior guardian dependency fails closed and permits configured inherited zone when present",()=>{const junior=entitlement({id:"junior",guardianRequired:true,accessZone:"general"});assert.equal(resolve([junior],undefined,{guardianPresent:false}).reasonCode,"GUARDIAN_REQUIRED");assert.equal(resolve([junior],undefined,{guardianPresent:true}).result,"ALLOWED");});
test("housing and digital-program capabilities do not create service access",()=>{const result=resolve([entitlement({id:"housing",key:"HOUSING",type:"housing",eventType:null,accessZone:null}),entitlement({id:"digital",key:"DIGITAL_PROGRAM",type:"content",eventType:null,accessZone:null})]);assert.equal(result.result,"DENIED");assert.equal(result.reasonCode,"NO_APPLICABLE_ENTITLEMENT");});
test("musical-only entitlement is isolated to the configured event type",()=>{const musical=entitlement({id:"musical",key:"MUSICAL_ENTRY",eventType:"midnight_musical",singleUse:true,usageLimit:1});assert.equal(resolve([musical]).result,"DENIED");const result=resolveAttendeeAccess({registrationStatus:"confirmed",credentialStatus:"active",eventOccurrence:{...occurrence,eventType:"midnight_musical"},entitlements:[musical],currentTime:"2026-11-03T19:05:00Z"});assert.equal(result.result,"ALLOWED");});
test("printed-program add-on never grants venue access",()=>{assert.equal(resolve([entitlement({id:"printed",key:"PRINTED_PROGRAM",type:"item",eventType:null,accessZone:null})]).result,"DENIED");});
test("payment and credential state remain authoritative",()=>{assert.equal(resolve([],undefined,{registrationStatus:"payment_pending"}).reasonCode,"PAYMENT_NOT_CONFIRMED");assert.equal(resolve([],undefined,{credentialStatus:"revoked"}).reasonCode,"CREDENTIAL_REVOKED");});
