import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const root=process.cwd(); const source=(path:string)=>readFile(`${root}/${path}`,"utf8");

test("normalized product entitlement migration is secure and seeds no products",async()=>{const sql=await source("supabase/migrations/20260806220000_registration_products_entitlements.sql");assert.match(sql,/CREATE TABLE IF NOT EXISTS public\.registration_products/);assert.match(sql,/CREATE TABLE IF NOT EXISTS public\.access_entitlements/);assert.match(sql,/CREATE TABLE IF NOT EXISTS public\.registration_product_entitlements/);assert.match(sql,/CREATE TABLE IF NOT EXISTS public\.attendee_entitlements/);assert.match(sql,/registration_product_id uuid NULL REFERENCES public\.registration_products/);assert.match(sql,/ENABLE ROW LEVEL SECURITY/);assert.match(sql,/FORCE ROW LEVEL SECURITY/);assert.match(sql,/REVOKE ALL .* FROM PUBLIC, anon, authenticated/);assert.doesNotMatch(sql,/INSERT INTO public\.(registration_products|access_entitlements)/);});
test("owner API is authenticated, program scoped, and uses controlled entitlement types",async()=>{const api=await source("app/api/owner/registration-products/route.ts");assert.match(api,/requireOwnerUser/);assert.match(api,/DEFAULT_PROGRAM_KEY/);assert.match(api,/ENTITLEMENT_TYPES/);assert.match(api,/registration_product_entitlements/);assert.doesNotMatch(api,/Diamond|General Registration|Musical Ticket/);});
test("owner UI has persisted product, entitlement, and assignment controls",async()=>{const [page,client,menu,management]=await Promise.all([source("app/owner/registrations/products/page.tsx"),source("components/owner/RegistrationProductAccessClient.tsx"),source("components/owner/OwnerProductionSideMenu.tsx"),source("app/owner/registrations/page.tsx")]);assert.match(page,/RegistrationProductAccessClient/);assert.match(client,/\/api\/owner\/registration-products/);assert.match(client,/method:\s*"POST"/);assert.match(client,/method:\s*"PATCH"/);assert.match(client,/Publish to attendees/);assert.match(menu,/\/owner\/registrations/);assert.match(management,/\/owner\/registrations\/products/);});
test("access authorization does not branch on product display names",async()=>{const resolver=await source("lib/registration/entitlements.ts");assert.match(resolver,/resolveAttendeeAccess/);assert.doesNotMatch(resolver,/Diamond|General Registration|2-Night|Musical Ticket/);});
