"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/exhaustive-deps */
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { SALUTATIONS } from "@/lib/registration/slice2-validation";
import RegistrationPolicyDocument from "@/components/registration/RegistrationPolicyDocument";
import HousingExperience from "@/components/housing/HousingExperience";

type Experience = { products:any[]; group:any|null; policy:any|null };
const blank:any={productId:"",salutation:"",firstName:"",lastName:"",suffix:"",email:"",mobilePhone:"",assistantEmail:"",streetAddress:"",addressLine2:"",city:"",state:"",postalCode:"",countryCode:"US",gender:"",requiresInterpretation:false,preferredLanguage:"",churchName:"",pastorName:"",jurisdiction:""};

export default function RegistrationSlice2Experience({initial}:{initial:Experience}) {
  const router=useRouter(), [data,setData]=useState(initial), [step,setStep]=useState(1), [error,setError]=useState(""), [busy,setBusy]=useState(false);
  const primary=data.group?.registrations?.find((r:any)=>r.is_primary_registrant);
  const [form,setForm]=useState<any>(primary?{...blank,id:primary.id,productId:primary.registration_product_id||"",firstName:primary.first_name||"",lastName:primary.last_name||"",email:primary.email||"",mobilePhone:primary.mobile_phone||"",streetAddress:primary.street_address||"",city:primary.city||"",state:primary.state||"",postalCode:primary.postal_code||"",countryCode:primary.country_code||"US",churchName:primary.church_name||"",pastorName:primary.pastor_name||"",jurisdiction:primary.jurisdiction||"",requiresInterpretation:primary.requires_interpretation,preferredLanguage:primary.preferred_language||""}:blank);
  const [member,setMember]=useState<any>({firstName:"",lastName:"",relationship:"spouse",productId:"",dateOfBirth:"",guardianRegistrationId:""});
  const members=data.group?.registrations??[], total=useMemo(()=>members.reduce((sum:number,row:any)=>sum+Number(row.amount_cents||0),0),[members]);
  async function call(body:any,method="POST",url="/api/registration/experience"){const response=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:method==="DELETE"?undefined:JSON.stringify(body)});const json=await response.json();if(!response.ok)throw new Error(json.error);return json;}
  async function reload(){const response=await fetch("/api/registration/experience",{cache:"no-store"});setData(await response.json());}
  async function save(registrant:any){setBusy(true);setError("");try{await call({action:"save_registrant",registrant});await reload();return true;}catch(e){setError(e instanceof Error?e.message:"Unable to save.");return false;}finally{setBusy(false);}}
  const field=(state:any,setter:any,name:string,label:string,type="text")=><label className="registration-field"><span className="registration-label">{label}</span><input required className="registration-input" type={type} value={state[name]??""} onChange={e=>setter({...state,[name]:e.target.value})}/></label>;
  async function saveMember(){const guardian=members.find((row:any)=>row.is_primary_registrant)?.id??null;const ok=await save({...blank,...form,...member,id:member.id,isPrimary:false,relationship:member.relationship,guardianRegistrationId:member.relationship==="child"?guardian:null,email:null,mobilePhone:null,assistantEmail:null,dateOfBirth:member.dateOfBirth||null});if(ok)setMember({firstName:"",lastName:"",relationship:"spouse",productId:"",dateOfBirth:"",guardianRegistrationId:""});}
  async function remove(id:string){setBusy(true);try{await call({},"DELETE",`/api/registration/experience?id=${encodeURIComponent(id)}`);await reload();}catch(e){setError(e instanceof Error?e.message:"Unable to remove.");}finally{setBusy(false);}}
  async function acceptPolicy(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const values=new FormData(event.currentTarget);setBusy(true);try{await call({action:"accept_policy",policyId:data.policy.id,authorizedSignerName:values.get("authorized"),agreementSignerName:values.get("agreement")});setStep(5);}catch(e){setError(e instanceof Error?e.message:"Unable to accept policy.");}finally{setBusy(false);}}
  async function submit(){setBusy(true);try{const result=await call({action:"submit_group"});if(result.status==="submitted")router.push("/register/review");else setStep(8);}catch(e){setError(e instanceof Error?e.message:"Unable to submit.");}finally{setBusy(false);}}
  return <section className="registration-shell" aria-labelledby="registration-title">
    <p className="registration-kicker">Holy Convocation registration</p><h1 id="registration-title" className="registration-title">{["","Attendee information","Registration type","Group / Junior registrants","Policy agreement","Housing","Review","Payment / Submit","Confirmation"][step]}</h1><p className="registration-progress">Step {step} of 8</p>{error?<p role="alert" className="registration-error-summary">{error}</p>:null}
    {step===1?<><div className="registration-fields"><label className="registration-field"><span className="registration-label">Salutation</span><select className="registration-input" value={form.salutation} onChange={e=>setForm({...form,salutation:e.target.value})}><option value="">Select</option>{SALUTATIONS.map(value=><option key={value}>{value}</option>)}</select></label>{field(form,setForm,"firstName","First name")}{field(form,setForm,"lastName","Last name")}{field(form,setForm,"suffix","Suffix")}{field(form,setForm,"email","Email","email")}{field(form,setForm,"mobilePhone","Cell phone","tel")}{field(form,setForm,"assistantEmail","Assistant email","email")}{field(form,setForm,"countryCode","Country code")}{field(form,setForm,"streetAddress","Address line 1")}{field(form,setForm,"addressLine2","Address line 2")}{field(form,setForm,"city","City")}{field(form,setForm,"state","State / Province")}{field(form,setForm,"postalCode","Postal code")}{field(form,setForm,"gender","Gender")}{field(form,setForm,"churchName","Church name")}{field(form,setForm,"pastorName","Pastor name")}{field(form,setForm,"jurisdiction","Jurisdiction")}<label><input type="checkbox" checked={form.requiresInterpretation} onChange={e=>setForm({...form,requiresInterpretation:e.target.checked,preferredLanguage:e.target.checked?form.preferredLanguage:""})}/> I require language interpretation</label>{form.requiresInterpretation?field(form,setForm,"preferredLanguage","Preferred interpretation language"):null}</div><button className="registration-btn registration-btn-primary" onClick={()=>setStep(2)}>Continue</button></>:null}
    {step===2?<><div className="grid gap-3">{data.products.length?data.products.map((product:any)=><label key={product.id} className="rounded border border-purple-400/30 p-4"><input type="radio" checked={form.productId===product.id} onChange={()=>setForm({...form,productId:product.id})}/> <strong>{product.name}</strong><span className="block text-sm">{product.description}</span><span>${(product.price_cents/100).toFixed(2)}</span>{product.eligibility_description?<small className="block">{product.eligibility_description}</small>:null}</label>):<p>No public registration products are currently available.</p>}</div><div className="registration-actions"><button className="registration-btn registration-btn-secondary" onClick={()=>setStep(1)}>Back</button><button disabled={!form.productId||busy} className="registration-btn registration-btn-primary" onClick={async()=>{if(await save({...form,isPrimary:true}))setStep(3);}}>Save and continue</button></div></>:null}
    {step===3?<><ul className="grid gap-2">{members.map((row:any)=><li key={row.id} className="flex justify-between rounded border border-white/10 p-3"><span>{row.first_name} {row.last_name} — {row.is_primary_registrant?"Primary":row.relationship_to_primary}</span>{!row.is_primary_registrant?<span><button onClick={()=>setMember({id:row.id,firstName:row.first_name,lastName:row.last_name,relationship:row.relationship_to_primary,productId:row.registration_product_id,dateOfBirth:row.date_of_birth||""})}>Edit</button> · <button onClick={()=>remove(row.id)}>Remove</button></span>:null}</li>)}</ul><div className="registration-fields mt-4">{field(member,setMember,"firstName","Registrant first name")}{field(member,setMember,"lastName","Registrant last name")}<label className="registration-field"><span className="registration-label">Relationship</span><select className="registration-input" value={member.relationship} onChange={e=>setMember({...member,relationship:e.target.value})}><option value="spouse">Spouse</option><option value="adjutant">Adjutant</option><option value="child">Child</option><option value="traveling_companion">Traveling companion</option><option value="other">Other</option></select></label>{member.relationship==="child"?field(member,setMember,"dateOfBirth","Junior date of birth","date"):null}<label className="registration-field"><span className="registration-label">Registration product</span><select required className="registration-input" value={member.productId} onChange={e=>setMember({...member,productId:e.target.value})}><option value="">Select</option>{data.products.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button disabled={busy} className="registration-btn registration-btn-secondary" onClick={saveMember}>{member.id?"Update registrant":"Add registrant"}</button></div><div className="registration-actions"><button className="registration-btn registration-btn-secondary" onClick={()=>setStep(2)}>Back</button><button className="registration-btn registration-btn-primary" onClick={()=>setStep(4)}>Continue</button></div></>:null}
    {step===4?(data.policy?<form onSubmit={acceptPolicy}><RegistrationPolicyDocument className="max-h-80 overflow-auto rounded border border-yellow-500/30 p-4" title={data.policy.title} version={data.policy.version} content={data.policy.content} effectiveAt={data.policy.effective_at}/><label className="registration-field"><span className="registration-label">Authorized/responsible person full name</span><input required name="authorized" className="registration-input"/></label><label className="registration-field"><span className="registration-label">Agreement full name</span><input required name="agreement" className="registration-input"/></label><button disabled={busy} className="registration-btn registration-btn-primary">Accept policy</button></form>:<p>No published registration policy is available. Submission is disabled.</p>):null}
    {step===5?<HousingExperience onComplete={()=>setStep(6)}/>:null}
    {step===6?<><dl className="registration-summary">{members.map((row:any)=><div key={row.id}><dt>{row.first_name} {row.last_name}</dt><dd>${(Number(row.amount_cents||0)/100).toFixed(2)}</dd></div>)}<div><dt>Registration total due</dt><dd>${(total/100).toFixed(2)}</dd></div></dl><p>Housing deposits are separate from registration payment and are never included in this total.</p><button className="registration-btn registration-btn-primary" onClick={()=>setStep(7)}>Proceed</button></>:null}
    {step===7?<button disabled={busy} className="registration-btn registration-btn-primary" onClick={submit}>{total>0?"Submit and continue to payment":"Complete free registration"}</button>:null}
    {step===8?<><h2>You&apos;re Registered!</h2><p>Next: Plan Your Trip. Now let&apos;s plan your trip to St. Louis. Travel is optional and can be completed later.</p><div className="registration-actions"><a className="registration-btn registration-btn-primary" href="/travel">Plan My Trip</a><a className="registration-btn registration-btn-secondary" href="/my-convocation">I&apos;ll Do This Later</a></div></>:null}
  </section>;
}
