-- Registration Slice 4: configurable hotels, blocks, preferences, requests, inventory, and audit.
-- No hotels, blocks, availability, requests, or contact details are seeded.
CREATE TABLE public.housing_hotels(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),program_key text NOT NULL DEFAULT 'cogic-stream-2026',name text NOT NULL,description text NULL,address_line_1 text NOT NULL,address_line_2 text NULL,city text NOT NULL,state text NOT NULL,postal_code text NOT NULL,website_url text NULL,map_url text NULL,photo_url text NULL,operator_notes text NULL,active boolean NOT NULL DEFAULT false,display_order integer NOT NULL DEFAULT 0,created_by uuid NULL REFERENCES auth.users(id) ON DELETE SET NULL,updated_by uuid NULL REFERENCES auth.users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(program_key,name));
CREATE TABLE public.housing_blocks(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),program_key text NOT NULL DEFAULT 'cogic-stream-2026',hotel_id uuid NOT NULL REFERENCES public.housing_hotels(id) ON DELETE RESTRICT,eligibility_entitlement_id uuid NOT NULL REFERENCES public.access_entitlements(id) ON DELETE RESTRICT,name text NOT NULL,minimum_nights integer NOT NULL CHECK(minimum_nights>0),maximum_nights integer NULL CHECK(maximum_nights IS NULL OR maximum_nights>0),earliest_arrival date NULL,latest_arrival date NULL,request_opens_at timestamptz NULL,request_closes_at timestamptz NULL,inventory_mode text NOT NULL CHECK(inventory_mode IN('REQUEST_ONLY','AUTHORITATIVE_INVENTORY')),capacity integer NULL CHECK(capacity IS NULL OR capacity>=0),reserved_count integer NOT NULL DEFAULT 0 CHECK(reserved_count>=0),occupancy_options jsonb NOT NULL DEFAULT '["Single","Double","Triple","Quad"]'::jsonb,deposit_notice text NULL,active boolean NOT NULL DEFAULT false,display_order integer NOT NULL DEFAULT 0,created_by uuid NULL REFERENCES auth.users(id) ON DELETE SET NULL,updated_by uuid NULL REFERENCES auth.users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CHECK(maximum_nights IS NULL OR maximum_nights>=minimum_nights),CHECK(latest_arrival IS NULL OR earliest_arrival IS NULL OR latest_arrival>=earliest_arrival),CHECK(request_closes_at IS NULL OR request_opens_at IS NULL OR request_closes_at>request_opens_at),CHECK((inventory_mode='REQUEST_ONLY' AND capacity IS NULL) OR (inventory_mode='AUTHORITATIVE_INVENTORY' AND capacity IS NOT NULL AND reserved_count<=capacity)),UNIQUE(program_key,hotel_id,name));
CREATE TABLE public.housing_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),program_key text NOT NULL DEFAULT 'cogic-stream-2026',user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,registration_group_id uuid NOT NULL REFERENCES public.registration_groups(id) ON DELETE RESTRICT,primary_registration_id uuid NOT NULL REFERENCES public.registrations(id) ON DELETE RESTRICT,housing_entitlement_id uuid NULL REFERENCES public.access_entitlements(id) ON DELETE RESTRICT,preference text NOT NULL CHECK(preference IN('book_hotel','book_later','sharing_room','own_accommodations')),hotel_id uuid NULL REFERENCES public.housing_hotels(id) ON DELETE RESTRICT,block_id uuid NULL REFERENCES public.housing_blocks(id) ON DELETE RESTRICT,arrival_date date NULL,departure_date date NULL,stay_nights integer NULL CHECK(stay_nights IS NULL OR stay_nights>0),occupancy text NULL,sharing_room boolean NOT NULL DEFAULT false,room_reservation_owner boolean NOT NULL DEFAULT false,status text NOT NULL DEFAULT 'draft' CHECK(status IN('draft','submitted','pending','confirmed','declined','canceled')),deposit_status text NOT NULL DEFAULT 'not_applicable' CHECK(deposit_status IN('not_applicable','pending','confirmed','failed')),owner_notes text NULL,confirmed_at timestamptz NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CHECK((preference='book_hotel' AND hotel_id IS NOT NULL AND block_id IS NOT NULL AND arrival_date IS NOT NULL AND departure_date IS NOT NULL AND occupancy IS NOT NULL AND room_reservation_owner) OR preference<>'book_hotel'),CHECK((preference='sharing_room' AND sharing_room) OR preference<>'sharing_room'));
CREATE UNIQUE INDEX housing_one_active_room_request_per_group ON public.housing_requests(registration_group_id) WHERE preference='book_hotel' AND status IN('draft','submitted','pending','confirmed');
CREATE TABLE public.housing_request_registrants(request_id uuid NOT NULL REFERENCES public.housing_requests(id) ON DELETE CASCADE,registration_id uuid NOT NULL REFERENCES public.registrations(id) ON DELETE RESTRICT,relationship text NULL,PRIMARY KEY(request_id,registration_id));
CREATE TABLE public.housing_audit_log(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,request_id uuid NULL REFERENCES public.housing_requests(id) ON DELETE SET NULL,actor_user_id uuid NULL REFERENCES auth.users(id) ON DELETE SET NULL,action text NOT NULL,details jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.housing_settings(program_key text PRIMARY KEY,support_name text NULL,support_email text NULL,support_phone text NULL,attendee_disclaimer text NULL,updated_by uuid NULL REFERENCES auth.users(id) ON DELETE SET NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX housing_requests_owner_idx ON public.housing_requests(user_id,created_at DESC);CREATE INDEX housing_requests_ops_idx ON public.housing_requests(status,hotel_id,block_id,arrival_date);CREATE INDEX housing_blocks_public_idx ON public.housing_blocks(program_key,active,display_order);

CREATE OR REPLACE FUNCTION public.submit_housing_request(p_user_id uuid,p_program_key text,p_preference text,p_block_id uuid DEFAULT NULL,p_arrival date DEFAULT NULL,p_departure date DEFAULT NULL,p_occupancy text DEFAULT NULL,p_registration_ids uuid[] DEFAULT NULL) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE g registration_groups%ROWTYPE; primary_id uuid; b housing_blocks%ROWTYPE; nights integer; eligible boolean:=false; rid uuid; request_id uuid; pref text:=p_preference;
BEGIN
 IF pref NOT IN('book_hotel','book_later','sharing_room','own_accommodations') THEN RAISE EXCEPTION 'Invalid accommodation preference'; END IF;
 SELECT * INTO g FROM registration_groups WHERE owner_user_id=p_user_id AND program_key=p_program_key;IF NOT FOUND THEN RAISE EXCEPTION 'Registration group not found';END IF;
 SELECT id INTO primary_id FROM registrations WHERE registration_group_id=g.id AND is_primary_registrant LIMIT 1;IF primary_id IS NULL THEN RAISE EXCEPTION 'Primary registration not found';END IF;
 IF pref='book_hotel' THEN
  SELECT * INTO b FROM housing_blocks WHERE id=p_block_id AND program_key=p_program_key AND active FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'Housing block unavailable';END IF;
  IF (b.request_opens_at IS NOT NULL AND now()<b.request_opens_at) OR (b.request_closes_at IS NOT NULL AND now()>=b.request_closes_at) THEN RAISE EXCEPTION 'Housing request window is closed';END IF;
  SELECT EXISTS(SELECT 1 FROM attendee_entitlements ae JOIN access_entitlements e ON e.id=ae.entitlement_id WHERE ae.user_id=p_user_id AND ae.status='active' AND e.id=b.eligibility_entitlement_id AND e.entitlement_type='housing') OR EXISTS(SELECT 1 FROM registrations r JOIN registration_product_entitlements pe ON pe.registration_product_id=r.registration_product_id AND pe.active JOIN access_entitlements e ON e.id=pe.entitlement_id WHERE r.registration_group_id=g.id AND r.is_primary_registrant AND e.id=b.eligibility_entitlement_id AND e.entitlement_type='housing' AND e.active) INTO eligible;
  IF NOT eligible THEN RAISE EXCEPTION 'Registration is not eligible for this housing block';END IF;
  nights:=p_departure-p_arrival;IF p_arrival IS NULL OR p_departure IS NULL OR nights<b.minimum_nights OR (b.maximum_nights IS NOT NULL AND nights>b.maximum_nights) THEN RAISE EXCEPTION 'Stay length does not satisfy block requirements';END IF;
  IF (b.earliest_arrival IS NOT NULL AND p_arrival<b.earliest_arrival) OR (b.latest_arrival IS NOT NULL AND p_arrival>b.latest_arrival) THEN RAISE EXCEPTION 'Arrival date is outside block requirements';END IF;
  IF NOT (b.occupancy_options ? p_occupancy) THEN RAISE EXCEPTION 'Invalid room occupancy';END IF;
  IF b.inventory_mode='AUTHORITATIVE_INVENTORY' THEN IF b.reserved_count>=b.capacity THEN RAISE EXCEPTION 'Housing block sold out';END IF;UPDATE housing_blocks SET reserved_count=reserved_count+1 WHERE id=b.id;END IF;
 END IF;
 INSERT INTO housing_requests(program_key,user_id,registration_group_id,primary_registration_id,housing_entitlement_id,preference,hotel_id,block_id,arrival_date,departure_date,stay_nights,occupancy,sharing_room,room_reservation_owner,status,deposit_status) VALUES(p_program_key,p_user_id,g.id,primary_id,CASE WHEN pref='book_hotel' THEN b.eligibility_entitlement_id ELSE NULL END,pref,CASE WHEN pref='book_hotel' THEN b.hotel_id ELSE NULL END,p_block_id,p_arrival,p_departure,nights,p_occupancy,pref='sharing_room',pref='book_hotel',CASE WHEN pref='book_hotel' THEN 'submitted' ELSE 'submitted' END,'not_applicable') RETURNING id INTO request_id;
 FOREACH rid IN ARRAY COALESCE(p_registration_ids,ARRAY[primary_id]) LOOP IF EXISTS(SELECT 1 FROM registrations WHERE id=rid AND registration_group_id=g.id) THEN INSERT INTO housing_request_registrants(request_id,registration_id) VALUES(request_id,rid) ON CONFLICT DO NOTHING;END IF;END LOOP;
 INSERT INTO housing_audit_log(request_id,actor_user_id,action,details) VALUES(request_id,p_user_id,'request_submitted',jsonb_build_object('preference',pref));RETURN request_id;
END $$;
CREATE OR REPLACE FUNCTION public.transition_housing_request(p_request_id uuid,p_status text,p_actor_user_id uuid,p_notes text DEFAULT NULL) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$ BEGIN IF p_status NOT IN('pending','confirmed','declined','canceled') THEN RAISE EXCEPTION 'Invalid housing status';END IF;UPDATE housing_requests SET status=p_status,owner_notes=p_notes,confirmed_at=CASE WHEN p_status='confirmed' THEN now() ELSE confirmed_at END,updated_at=now() WHERE id=p_request_id;IF NOT FOUND THEN RETURN false;END IF;INSERT INTO housing_audit_log(request_id,actor_user_id,action,details) VALUES(p_request_id,p_actor_user_id,'status_'||p_status,jsonb_build_object('notes',p_notes));RETURN true;END $$;

ALTER TABLE public.housing_hotels ENABLE ROW LEVEL SECURITY;ALTER TABLE public.housing_hotels FORCE ROW LEVEL SECURITY;ALTER TABLE public.housing_blocks ENABLE ROW LEVEL SECURITY;ALTER TABLE public.housing_blocks FORCE ROW LEVEL SECURITY;ALTER TABLE public.housing_requests ENABLE ROW LEVEL SECURITY;ALTER TABLE public.housing_requests FORCE ROW LEVEL SECURITY;ALTER TABLE public.housing_request_registrants ENABLE ROW LEVEL SECURITY;ALTER TABLE public.housing_request_registrants FORCE ROW LEVEL SECURITY;ALTER TABLE public.housing_audit_log ENABLE ROW LEVEL SECURITY;ALTER TABLE public.housing_audit_log FORCE ROW LEVEL SECURITY;ALTER TABLE public.housing_settings ENABLE ROW LEVEL SECURITY;ALTER TABLE public.housing_settings FORCE ROW LEVEL SECURITY;
REVOKE ALL ON public.housing_hotels,public.housing_blocks,public.housing_requests,public.housing_request_registrants,public.housing_audit_log,public.housing_settings FROM PUBLIC,anon,authenticated;GRANT ALL ON public.housing_hotels,public.housing_blocks,public.housing_requests,public.housing_request_registrants,public.housing_audit_log,public.housing_settings TO service_role;REVOKE ALL ON FUNCTION public.submit_housing_request(uuid,text,text,uuid,date,date,text,uuid[]),public.transition_housing_request(uuid,text,uuid,text) FROM PUBLIC,anon,authenticated;GRANT EXECUTE ON FUNCTION public.submit_housing_request(uuid,text,text,uuid,date,date,text,uuid[]),public.transition_housing_request(uuid,text,uuid,text) TO service_role;
