-- COGIC Travel foundation. No hotels, prices, inventory, or bookings are seeded.
create table public.travel_hotels(id uuid primary key default gen_random_uuid(),program_key text not null default 'cogic-stream-2026',name text not null,description text,image_url text,address text not null,city text not null,state text not null,postal_code text not null,latitude numeric,longitude numeric,distance_label text,official_cogic boolean not null default true,negotiated_rate_cents integer check(negotiated_rate_cents is null or negotiated_rate_cents>=0),reference_rate_cents integer check(reference_rate_cents is null or reference_rate_cents>=0),rate_currency text not null default 'USD',booking_url text,booking_code text,booking_deadline date,availability_message text,amenities text[] not null default '{}',parking_info text,breakfast_info text,shuttle_info text,accessibility_info text,map_url text,published boolean not null default false,archived boolean not null default false,display_order integer not null default 0,created_by uuid references auth.users(id) on delete set null,updated_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(program_key,name));
create table public.travel_hotel_blocks(id uuid primary key default gen_random_uuid(),program_key text not null default 'cogic-stream-2026',hotel_id uuid not null references public.travel_hotels(id) on delete restrict,name text not null,booking_url text,booking_code text,deadline date,availability_message text,published boolean not null default false,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.travel_airports(id uuid primary key default gen_random_uuid(),program_key text not null default 'cogic-stream-2026',iata_code text not null,name text not null,guidance text,url text,published boolean not null default false,display_order integer not null default 0,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.travel_transportation_options(id uuid primary key default gen_random_uuid(),program_key text not null default 'cogic-stream-2026',kind text not null check(kind in('airport_transfer','official_shuttle','hotel_shuttle','rideshare','public_transit','parking','charter_bus','other')),name text not null,description text,url text,published boolean not null default false,display_order integer not null default 0,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.travel_announcements(id uuid primary key default gen_random_uuid(),program_key text not null default 'cogic-stream-2026',title text not null,body text not null,published boolean not null default false,published_at timestamptz,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.travel_provider_configs(id uuid primary key default gen_random_uuid(),program_key text not null default 'cogic-stream-2026',provider_key text not null,enabled boolean not null default false,affiliate_attribution_id text,settings jsonb not null default '{}',updated_by uuid references auth.users(id) on delete set null,updated_at timestamptz not null default now(),unique(program_key,provider_key));
create table public.user_trips(id uuid primary key default gen_random_uuid(),program_key text not null default 'cogic-stream-2026',user_id uuid not null references auth.users(id) on delete cascade,registration_id uuid references public.registrations(id) on delete set null,status text not null default 'not_started' check(status in('not_started','planning','trip_added')),party_type text check(party_type is null or party_type in('alone','family','church','jurisdiction_group')),party_size integer check(party_size is null or party_size>0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(program_key,user_id));
create table public.user_trip_hotels(id uuid primary key default gen_random_uuid(),trip_id uuid not null references public.user_trips(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,hotel_name text not null,confirmation_number text,check_in date,check_out date,address text,booked_externally boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(check_out is null or check_in is null or check_out>=check_in));
create table public.user_trip_flights(id uuid primary key default gen_random_uuid(),trip_id uuid not null references public.user_trips(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,airline text not null,flight_number text,origin text not null,destination text not null,departure_at timestamptz not null,arrival_at timestamptz,confirmation_number text,booked_externally boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.user_trip_cars(id uuid primary key default gen_random_uuid(),trip_id uuid not null references public.user_trips(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,company text not null,confirmation_number text,pickup_at timestamptz not null,dropoff_at timestamptz,booked_externally boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.travel_analytics_events(id bigint generated always as identity primary key,program_key text not null default 'cogic-stream-2026',user_id uuid references auth.users(id) on delete set null,event_name text not null,properties jsonb not null default '{}',created_at timestamptz not null default now());
create index travel_hotels_public_idx on public.travel_hotels(program_key,published,archived,display_order);create index user_trip_hotels_owner_idx on public.user_trip_hotels(user_id);create index user_trip_flights_owner_idx on public.user_trip_flights(user_id);create index user_trip_cars_owner_idx on public.user_trip_cars(user_id);create index travel_analytics_program_idx on public.travel_analytics_events(program_key,event_name,created_at);
alter table public.registrations add column if not exists travel_party_type text check(travel_party_type is null or travel_party_type in('alone','family','church','jurisdiction_group')),add column if not exists travel_party_size integer check(travel_party_size is null or travel_party_size>0);
alter table public.travel_hotels enable row level security;alter table public.travel_hotel_blocks enable row level security;alter table public.travel_airports enable row level security;alter table public.travel_transportation_options enable row level security;alter table public.travel_announcements enable row level security;alter table public.travel_provider_configs enable row level security;alter table public.user_trips enable row level security;alter table public.user_trip_hotels enable row level security;alter table public.user_trip_flights enable row level security;alter table public.user_trip_cars enable row level security;alter table public.travel_analytics_events enable row level security;
create policy travel_hotels_public_read on public.travel_hotels for select using(published and not archived);create policy travel_airports_public_read on public.travel_airports for select using(published);create policy travel_transport_public_read on public.travel_transportation_options for select using(published);create policy travel_announcements_public_read on public.travel_announcements for select using(published);
create policy user_trips_owner_all on public.user_trips for all using(auth.uid()=user_id) with check(auth.uid()=user_id);create policy user_trip_hotels_owner_all on public.user_trip_hotels for all using(auth.uid()=user_id) with check(auth.uid()=user_id);create policy user_trip_flights_owner_all on public.user_trip_flights for all using(auth.uid()=user_id) with check(auth.uid()=user_id);create policy user_trip_cars_owner_all on public.user_trip_cars for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
revoke all on public.travel_provider_configs from anon,authenticated;grant all on public.travel_provider_configs to service_role;
